require 'numbers_and_words/strategies/figures_converter/options/vi/hundreds_with_union'
require 'numbers_and_words/strategies/figures_converter/options/vi/remove_hyphen'
require 'numbers_and_words/strategies/figures_converter/options/vi/ordinal'
require 'numbers_and_words/strategies/figures_converter/options/vi/pronounced'
require 'numbers_and_words/strategies/figures_converter/options/vi/remove_zero'
